services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: 
        - /bin/sh
        - -c
        - | 
           python ecommerce_site/manage.py migrate 
           python ecommerce_site/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

volumes:
  pg_data: