services:
  db:
    image: postgres:latest
    env_file:
      - ./.env.prod.db
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: 
        - /bin/sh
        - -c
        - | 
           python ecommerce_site/manage.py migrate 
           python ecommerce_site/manage.py runserver 0.0.0.0:8000
          #  gunicorn ecommerce_site.wsgi:application --bind 0.0.0.0:8000 --chdir ecommerce_site
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

volumes:
  pg_data: