version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: DockerfileForRDS
    command: 
        - /bin/sh
        - -c
        - | 
          python ecommerce_site/manage.py migrate 
          #  python ecommerce_site/manage.py runserver 0.0.0.0:8000
          gunicorn ecommerce_site.wsgi:application --bind 0.0.0.0:8000 --chdir ecommerce_site
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.rds
